<?php
/** @var \Mirasvit\GdprCookie\Block\SettingsModal $block */
/** @var \Hyva\Theme\Model\ViewModelRegistry $viewModels */
/** @var \Hyva\Theme\ViewModel\HeroiconsOutline $heroicons */
/** @var \Magento\Framework\Escaper $escaper */
$heroicons = $viewModels->require(\Hyva\Theme\ViewModel\HeroiconsOutline::class);

?>

<div class="relative z-30"
     x-data="initGdprSettingsModal()" x-init="init()">
    <div class="fixed w-full h-full flex items-center justify-center" x-show="open">
        <div class="absolute bg-black h-full opacity-50 w-full" x-on:click="close"
             style="display: none"
             x-show="open"></div>
        <div class="bg-white border border-gray-200 content h-full lg:max-w-4xl max-w-sm md:h-4/6 md:max-w-md overflow-auto overscroll-contain p-12 rounded-md z-20"
             style="display: none"
             x-show.transition.origin.top="open">
            <div class="border-b border-gray-500 flex justify-between mb-3 pb-4">
                <h3 class="text-3xl"><?= $escaper->escapeHtml($block->getPopupTitle()) ?></h3>
                <div class="cursor-pointer pt-1"
                     x-on:click="close"><?= $heroicons->xHtml('w-6 h-6', 6, 6); ?></div>
            </div>
            <?= $escaper->escapeHtml($block->getPopupDescription()); ?>
            <div class="group-content">
                <?php foreach ($block->getCookieGroups() as $group): ?>
                    <?= /* @noEscape */ $block->getCookieGroupHtml($group); ?>
                <?php endforeach; ?>
                <?php if ($block->isGoogleConsentModeEnabled()): ?>
                    <div class="google-consent-container border border-gray-300 mt-4 p-3 rounded-2xl shadow-sm"
                         x-data="{open_google_consent_settings: false}">

                        <div class="flex flex justify-between">
                            <h4 class="title text-lg cursor-pointer"
                                x-on:click="open_google_consent_settings = !open_google_consent_settings">
                                <span
                                    x-show="! open_google_consent_settings"><?= $heroicons->chevronUpHtml('h-6 inline mr-2 w-6', 4, 4); ?></span>
                                <span x-show="open_google_consent_settings"
                                      style="display: none"><?= $heroicons->chevronDownHtml('h-6 inline mr-2 w-6', 4, 4); ?></span>
                                <?= $escaper->escapeHtml(__('Google Consent')); ?>
                            </h4>
                        </div>

                        <div class="content mt-4 pl-5" x-show.transition.origin.top="open_google_consent_settings"
                             style="display: none">
                            <div class="cookie-list">
                                <table>
                                    <?php foreach ($block->getGoogleConsentTypes() as $type): ?>
                                        <tr>
                                            <td class="p-2"><?= /* @noEscape */$type ?></td>
                                            <td class="p-2">
                                                <input class="checkbox disabled:opacity-40" type="checkbox" value="1"
                                                       name="google_consent_<?= /* @noEscape */$type ?>"
                                                       data-consent-type="<?= /* @noEscape */$type ?>">
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                </table>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
            <button class="btn btn-primary ml-auto mt-4 text-sm cursor-pointer"
                    x-on:click="save"><span><?= $escaper->escapeHtml(__('Apply')) ?></span></button></div>
    </div>
</div>
<script>
    function initGdprSettingsModal() {
        return {
            open: false,
            close: function () {
                this.open = false;
                document.querySelector('body').style.overflow = 'auto';
            },
            init: function () {
                window.addEventListener('mst-gdpr-cookie-settings-open', () => {
                    document.querySelector('body').style.overflow = 'hidden';
                    this.open = true;
                })
            },
            save: function () {
                window.dispatchEvent(new CustomEvent('mst-gdpr-cookie-settings-save'));
                this.close();
            }
        };
    }
</script>
