<?php
/** @var \Magento\Framework\Escaper $escaper */

use Magento\Framework\Escaper;

/** @var \Mirasvit\Gdpr\Block\Customer\Account\Consents $block */
$collection = $block->getAllCustomerConsents();
?>
<div class="block">
    <div class="mb-6 text-2xl block-title"><?= $escaper->escapeHtml(__('My Consent Choices')) ?></div>


    <div class="block-content overflow-x-auto card mb-4">
        <div class="table-wrapper orders-recent">
            <?php
            if ($collection && $collection->count()): ?>
                <?= $block->getToolbarHtml() ?>
                <table class="data-table table w-full sm:table-fixed lg:table-auto">
                    <thead class="text-sm text-secondary">
                    <tr>
                        <th class="p-2 text-start"><?= $escaper->escapeHtml(__('ID')) ?></th>
                        <th class="p-2 text-start"><?= $escaper->escapeHtml(__('Ip')) ?></th>
                        <th class="p-2 text-start"><?= $escaper->escapeHtml(__('Consent Type')) ?></th>
                        <th class="p-2 text-start"><?= $escaper->escapeHtml(__('Created')) ?></th>
                        <th class="p-2 text-start"><?= $escaper->escapeHtml(__('Cookie Groups')) ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    foreach ($collection as $consent): ?>
                        <tr class="align-top even:bg-container-darker">
                            <td class="p-2 hidden lg:table-cell" data-th="<?= $escaper->escapeHtml(__('ID')) ?>"><?= $escaper->escapeHtml($consent->getId()) ?></td>
                            <td class="p-2 hidden lg:table-cell" data-th="<?= $escaper->escapeHtml(__('Ip')) ?>"><?= $escaper->escapeHtml(__($consent->getRemoteAddr())) ?></td>
                            <td class="p-2 hidden lg:table-cell" data-th="<?= $escaper->escapeHtml(__('Consent Type')) ?>"><?= $escaper->escapeHtml(__($consent->getType())) ?></td>
                            <td class="p-2 hidden lg:table-cell" data-th="<?= $escaper->escapeHtml(__('Created')) ?>"><?= $escaper->escapeHtml($consent->getCreatedAt()) ?></td>
                            <td class="p-2 hidden lg:table-cell" data-th="<?= $escaper->escapeHtml(__('Cookie Groups')) ?>"><?= $escaper->escapeHtml($block->getCookieGroupNames($consent)) ?></td>
                        </tr>
                    <?php
                    endforeach ?>
                    </tbody>
                </table>
            <?php
            else: ?>
                <p><?= $escaper->escapeHtml(__('You have no consents yet.')) ?></p>
            <?php
            endif ?>
        </div>

    </div>
</div>

