<?php
/** @var \Mirasvit\Gdpr\Block\Customer\Account\Dashboard $block */
?>
<div class="block">
    <div class="block-title">
        <strong><?= __('Privacy Dashboard') ?></strong>
    </div>
    <div class="block-content">
        <div class="mst_gdpr_dashboard_items">
            <ol>
                <li>
                    <a href="/privacy-policy-cookie-restriction-mode">Privacy Policy Cookie Restriction</a>
                </li>
            </ol>
            <ol>
                <li>
                    <a href="anonymize">Anonymize my account</a>
                </li>
            </ol>
            <ol>
                <li>
                    <a href="download">Download personal data</a>
                </li>
            </ol>
            <ol>
                <li>
                    <a href="remove">Delete my account</a>
                </li>
            </ol>
        </div>
    </div>
</div>
