<?php
/** @var \Mirasvit\Gdpr\Block\Customer\Account\Anonymize $block */
?>
<div class="block mt-8">
    <div class="block-title text-xl">
        <strong><?= __('Download personal data') ?></strong>
    </div>

    <div class="block-content" x-data="{active: false}">
        <form method="post" action="<?= $block->getUrl('gdpr/customer/download') ?>">
            <input name="form_key" type="hidden" value="<?= $block->getFormKey() ?>"/>

            <fieldset class="fieldset" style="display: none" id="download-form" x-show="active">
                <div class="field required">
                    <label class="label" for="dl-current-password">
                        <span><?= __('Current Password') ?></span>
                    </label>
                    <div class="control">
                        <input id="dl-current-password" type="password" class="input-text" name="password" autocomplete="off" aria-required="true" required/>
                    </div>
                </div>

                <div class="actions-toolbar">
                    <button type="submit" class="action primary btn btn-primary">
                        <span><?= __('Download') ?></span>
                    </button>
                </div>
            </fieldset>
        </form>

        <div id="download-intro" x-show="! active">
            <p><?= __('You can download all your data that we have stored by clicking the button below:') ?></p>
            <div class="actions-toolbar">
                <button type="button" class="action btn" data-show="download-form" data-hide="download-intro" @click="active=true">
                    <span><?= __('Process') ?></span>
                </button>
            </div>
        </div>
    </div>
</div>
