<?php
/** @var \Mirasvit\Gdpr\Block\Customer\Account\Remove $block */
?>
<div class="block" mt-8>
    <div class="block-title text-xl">
        <strong><?= __('Delete account') ?></strong>
    </div>

    <div class="block-content" x-data="{active: false}">


        <form method="post" action="<?= $block->getUrl('gdpr/customer/remove') ?>">
            <input name="form_key" type="hidden" value="<?= $block->getFormKey() ?>"/>

            <fieldset class="fieldset" style="display: none" x-show="active" id="remove-form">
                <div class="field">
                    <p><strong><?= __('Please keep in mind that we are deleting your account. After the deletion of your account, you will not be able to access your account anymore.') ?></strong></p>
                </div>

                <div class="field required">
                    <label class="label" for="rm-current-password">
                        <span><?= __('Current Password') ?></span>
                    </label>
                    <div class="control">
                        <input id="rm-current-password" type="password" class="input-text" name="password" autocomplete="off" aria-required="true" required/>
                    </div>
                </div>

                <div class="field choice required">
                    <input type="checkbox" id="remove_accept" required name="accept" value="1" class="checkbox">
                    <label for="remove_accept" class="label"><span><?= __('I understand and want remove my personal data') ?></span></label>
                </div>

                <div class="actions-toolbar">
                    <button type="submit" class="action btn btn-primary">
                        <span><?= __('Send request') ?></span>
                    </button>
                </div>
            </fieldset>
        </form>

        <div id="remove-intro" x-show="!active">
            <p><?= __('You can request the deletion of your data that we have stored by clicking the button below:') ?></p>
            <div class="actions-toolbar">
                <button type="button" class="action btn" @click="active=true">
                    <span><?= __('Delete my account') ?></span>
                </button>
            </div>
        </div>
    </div>
</div>
